name: Build Check

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-checks:
    concurrency: ci-${{ github.ref }} 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1' # Not needed with a .ruby-version, .tool-versions or mise.toml
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install Antora Dependencies
      run: |
        cd antora
        gem install bundler
        bundle install
        npm install

    - name: Install Docusaurus dependencies
      run: yarn install

    - name: Build website
      run: |
        cd antora 
        npx antora antora-playbook.yml --stacktrace
        cd ..
        yarn build
